name: 'Send test coverage report to Codacy'
description: ''
inputs:
  project-token:
    required: true
    description: 'Codacy project token'
runs:
  using: 'composite'
  steps:
    - name: Build test coverage report
      shell: bash
      run: ./gradlew jacocoTestReport
    - name: Send test coverage report to Codacy
      uses: codacy/codacy-coverage-reporter-action@v1
      with:
        project-token: ${{ inputs.project-token }}
        coverage-reports: build/reports/jacoco/test/jacocoTestReport.xml
