name: "Docker Build & Push"
description: "Build and push a docker container image to container registry"
inputs:
  container_registry:
    required: false
    description: "The container registry URL"
    default: 'ghcr.io'
runs:
  using: 'composite'
  steps:
    - name: Build test coverage report
      shell: bash
      run: ./gradlew jacocoTestReport
    - name: Send test coverage report to Codacy
      uses: codacy/codacy-coverage-reporter-action@v1
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: build/reports/jacoco/test/jacocoTestReport.xml
