name: Build and run tests under Java using Gradle
on:
  workflow_call:
    inputs:
      java-version:
        description: 'Version of Java to run builds on'
        type: string
        required: true

jobs:
  build-and-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'corretto'
          cache: 'gradle'
      - name: Run a build
        run: ./gradlew compileJava --stacktrace
      - name: Run tests
        run: ./gradlew test
