name: Build and run tests under Java using Gradle
on:
  workflow_call:
    inputs:
      java-version:
        description: 'Version of Java to run builds on'
        type: string
        required: true
      codacy-report:
        description: 'Send or not test coverage report to Codacy'
        type: boolean
        required: false
        default: false
#concurrency:
#  group: ${{ github.workflow }}-${{ github.ref }}
#  cancel-in-progress: true
jobs:
  build-and-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'corretto'
          cache: 'gradle'
      - name: Run a build
        run: ./gradlew compileJava --stacktrace
      - name: Run tests
        run: ./gradlew test
      - name: Send test coverage report Codacy
        if: ${{ inputs.codacy-report }}
        uses: oleg-cherednik/action.yml@main
#      - name: Build test coverage report
#        if: ${{ inputs.codacy-report }}
#        run: ./gradlew jacocoTestReport
#      - name: Send test coverage report Codacy
#        if: ${{ inputs.codacy-report }}
#        uses: codacy/codacy-coverage-reporter-action@v1
#        with:
#          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
#          coverage-reports: build/reports/jacoco/test/jacocoTestReport.xml
